### ISSUE TITLE
Suggestion: ComponentsButton.CUSTOM_EMBED

### ISSUE THREAD

**Issue by Arcanocito** [Defxult/reactionmenu#11]
I noticed that the CUSTOM_EMBED ReactionMenu Button type was not added to the ButtonMenu.
I use this feature a lot in my Bot, so it would be nice to see this feature implemented here as well.

**Comment by Defxult** [comment]
This will be implemented. I decided not to have it on release because initially there were complications integrating that capability with buttons and their `custom_id`. The base of the workaround has been tested and successfully works with other IDs, but not fully tested with custom embeds. `ComponentsButton.ID_CUSTOM_EMBED` should be added either the end of this week or the next if everything works out while testing
