### ISSUE TITLE
How to add attachment when using ReactionMenu

### ISSUE THREAD

**Issue by TheSmartKing** [Defxult/reactionmenu#13]
How do I add an attached file to my menu? await menu.start() doesnt allow for the file parameter.

**Comment by Defxult** [comment]
Pagination doesn't include files. Pagination is just editing a message via `discord.Message.edit` and the edit method does not have a `file` parameter. If the `.start()` method was to include a file, you could see the file initially, but paginating back to that first initial page would not contain that file because of what I said in the first couple sentences.

**Comment by TheSmartKing** [comment]
The thing im trying to achieve is 
![afbeelding](https://user-images.githubusercontent.com/82277786/124257394-a0ef1880-db2c-11eb-9a1c-e7e0d0c0548f.png)
this, but I have the picture as attachment://filename.jpg

Its a local file. How would you suggest I go about this then?

**Comment by Defxult** [comment]
You'll have to put that local image online. Either a image hosting site such as Imgur or what I like to do, use discord as your image host. Post that image into a channel, then right click and get the URL. That way you can use it in the embed

**Comment by TheSmartKing** [comment]
Does Discord host the image forever? Or does is it deleted from their server and the link invalid after a while?

**Comment by Defxult** [comment]
The link stays valid as long as the message containing that image is not deleted. The first image you see in the README.md is hosted by discord. I have a private server and a channel where I put all the images I need in. Since it's a private server, I know the messages will not be deleted, thus the link remains valid.

**Comment by TheSmartKing** [comment]
Fair. Thank you!
