### ISSUE TITLE
Is it possible to add image urls in embed.set_image(url="image_url") section of Embed while using ReactionMenu.DYNAMIC?

### ISSUE THREAD

**Issue by felixsam359** [Defxult/reactionmenu#19]
Hi, thanks for making an powerful library, I don't have to hard code pagination functions anymore.

I'm trying to paginate some image URLs which I get from an API by using `ReactionMenu.DYNAMIC`. By default all the image URLs are added in the description section of the Embed. 

Is it possible in the future to added the image URLs in the `embed.set_image(url="image_url")` section of the embed?

By this feature one can paginate       mangas, comics and picture books in Discord using python.

```py
@bot.command()
async def pagination(ctx):
  x = ["https://img.xcitefun.net/users/20143.jpg", "https://img.xcitefun.net/users/20144.jpg",.....]  
  #A list of Image URLs 
  
  Embed = discord.Embed(title="Test", description = "lion eats rabbit" ,colour=0xff00ff)
  #My custom description gets overridden as described in Readme
  
  menu = ReactionMenu(ctx, back_button='◀️', next_button='▶️', config=ReactionMenu.DYNAMIC, rows_requested=1, custom_embed=Embed)
  
  for i in x:
    menu.add_row(i)
    
  await menu.start()
```

**Comment by Defxult** [comment]
Lets say you are making a picture book, yes you get the URLs from the API, but are you making your own sentences ("lion eats rabbit") or is that example sentence also from the API? Also, every time you fetch from the API, do you always get the same URLs back? Because from what it looks like, you might be able to use `ReactionMenu.STATIC`. As for future implantation, I'm not sure, but I'm leaning to probably not. It would be difficult for the library to know which pages you'd like images on because at it's core, `add_row()` just adds the data to each embed and makes a new one when the `rows_requested` limit has been reached, and there's no way to know which image belongs to what page upon each page completion.

The `custom_embed` isn't used in the correct way in your code. Custom embeds are purely cosmetic. Mainly for things like adding a color or title that you'd like the user to always see during the pagination process.

**Comment by felixsam359** [comment]
Hi,
I think you analysed my situation correctly.

-Yes I am trying to make a picture book.
-I get the image URLs from the API in a list.

-But I'm not making my own sentences. "Lion eats rabbit"  is neither from the API nor from mine side. I just wanted to fill the empty description with a random string and check if description gets replaced with the API data when I use `ReactionMenu.DYNAMIC`

-Every time I fetch the image URLs from the API I don't get same image URLs, I get different image URLs.

I don't have any deep knowledge in python but can't the library identify images by index number as they are in a list? 

I think that all picture-book and mangas those who provide APIs send images_urls in a well ordered list.

Index number 0 in list is page 1
Index number 1 in list is page 2
Index number 3 in list is page 3
.
.
Index number n in the list is the last page in the manga or picture book.

For example
```
['https://mangafox.com/mangas/Naruto/1.jpg', 'https://mangafox.com/mangas/Naruto/2.jpg', 'https://mangafox.com/mangas/Naruto/3.jpg', 'https://mangafox.com/mangas/Naruto/4.jpg', 'https://mangafox.com/mangas/Naruto/5.jpg', 'https://mangafox.com/mangas/Naruto/6.jpg', 'https://mangafox.com/mangas/Naruto/7.jpg', 'https://mangafox.com/mangas/Naruto/8.jpg', 'https://mangafox.com/mangas/Naruto/9.jpg', 'https://mangafox.com/mangas/Naruto/10.jpg'
]
```

I maybe wrong, because I'm still learning python.

**Comment by Defxult** [comment]
Yeah so if you already have all the URLs and just want to display them, use `ReactionMenu.STATIC`. The dynamic way is not what you're looking for even though I understand why you would think so. Because in your instance, sure you don't know how many URLs you'll get back/the URLs are different image URLs when you fetch from the API. But since you store the URLs into `list`, just loop through them and add them as embed pages

```py
@bot.command()
async def picturebook(ctx):
    menu = ReactionMenu(ctx, back_button='◀️', next_button='▶️', config=ReactionMenu.STATIC)
    api_urls = ['https://mangafox.com/mangas/Naruto/1.jpg', 'https://mangafox.com/mangas/Naruto/2.jpg', ...]

    for url in api_urls:
        embed = discord.Embed().set_image(url=url)
        menu.add_page(embed)
    
    await menu.start()
```

**Comment by felixsam359** [comment]
Yes, it solved my issue thanks!

**Comment by felixsam359** [comment]
`discord.py`'s official owner stopped maintaining the library, many developers are migrating to `pycord` or `nextcord`. 

What are your future plans for this cool project?

**Comment by Defxult** [comment]
I've been keeping my eye own both `pycord` and `nextcord`, and it seems like a decent amount of people are going for `pycord`. I've tested `pycord` and so far it works great. I had originally re-worked the library for discord.py 2.0, but since d.py was discontinued, `reactionmenu 3.0` was discontinued. But it seems like `pycord` might be the next reliable discord python library. Quite a few things have changed with `reactionmenu 3.0`, so I still am looking forward to releasing it.

As of yesterday, `pycord` is in public alpha, so I might release the alpha for `reactionmenu 3.0` in a 3.0 branch (using the `pycord` lib) in the following days. If everything goes well, `pycord` will be the new (and only) discord library for this library when it officially releases. Another branch will be made available for users who do not want to upgrade to the 2.0 version of the discord library, and this main branch will become the old branch (using discord.py 1.x and dislash.py).

**Comment by felixsam359** [comment]
Yea Danny discontinuing `discord.py` was the biggest plot twist in `discord.py` history. And yes `pycord` has 100 more stars compared to `nextcord`. Let's see what happens in future. `Pycord` gained popularity because they introduced slash commands pretty fast. `Nextcord` team are saying that `pycord` copied some library for making slash commands. 

I will stop coding for 14 days and see which branch comes out dominant. If I select the wrong library I have to rewrite everything.
 
I have a doubt. To avoid further conflicts in my projects(all of them are written in dpy) I changed my `pyproject.toml` likewise.

From 
```
reactionmenu = "^2.0.3"
```
to
```
reactionmenu = "2.0.3"
```
Am I doing the correct thing?

**Comment by Defxult** [comment]
Yes, that would be the best thing to do. Everything `reactionmenu 2.x` will be discord.py and dislash.py. I have no plans on updating the library on PyPI for version 2.x unless someone reports a critical bug. But the lib is pretty well tested, and the last verified bug that was reported is from June 2021. All updates will be going to 3.0 (only on GitHub until pycord releases), and setting it to `reactionmenu = "2.0.3"` will ensure whoever installs one of your projects in the future when I release 3.0 will be using the discord.py/dislash.py version.

It should be noted that since `reactionmenu 2.x` relies on dislash.py for it's Buttons functionality. If the dev of dislash.py decides to update the lib with any breaking changes, it's possible that the `ButtonsMenu` and `ComponentsButton` classes could break. And if those classes break because of dislash.py, your project breaks if you decide to use those classes. Using `ReactionMenu` and `Button` will be fine for future use if you're using discord.py.

I've seen my lib download statistics, and a majority of people still prefer to use reactions instead of Buttons for pagination. If you don't care about the Buttons feature and only care about pagination using reactions, I suggest setting it to `reactionmenu = "1.0.9"`. That is the last version that is only dependent on discord.py. But if you haven't read Danny's gist, come April 2022 discord.py will be almost useless because of discords breaking changes to their API. Just be mindful of the April 2022 deadline but you would have made a switch by then.
