### ISSUE TITLE
Reactionmenu in an on_message event

### ISSUE THREAD

**Issue by unadjusted** [Defxult/reactionmenu#31]
Tbh i wanted to make this an discussion... 
Not an option so i put this here:

**Issue?**
The reactionmenu does not pick up any reactions when used in an on_message event

**To Reproduce**
Since `ctx` is an required argument i defined it in an `on_message` event like so:
```py
ctx = await self.bot.get_context(message)
menu = ReactionMenu(ctx, back_button='◀️', next_button='▶️', config=ReactionMenu.STATIC)
for pos, val in enumerate(logs.getDataFromBattleLink(link), 1):
   menu.add_page(discord.Embed(title=f'**Turn {pos}**', description=f'>>> {val[0]}'))
await menu.start()
```

**Traceback if any**
```
No errors, same code works in an cmd
```

**!! Outdated !!**
**Required Checklist**
- [x] My Python version is 3.8 or higher
- [X] I use rmenulegacy, but both require ctx, so i thought i put this here
- [x] I am on d.py 1.7.3
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

Image 1.
![image](https://user-images.githubusercontent.com/85350984/158187999-1c1b7737-6d99-4353-baa8-c0d38e28b7a5.png)

Expected 2.
![image](https://user-images.githubusercontent.com/85350984/158187975-298bebc4-5a7b-4a80-8716-e9f13f0f3cc9.png)

**Comment by unadjusted** [comment]
![image](https://user-images.githubusercontent.com/85350984/158187295-612444b3-c025-43e4-ad20-88d3e35ae6dc.png)

**Comment by Defxult** [comment]
I've seen `rmenulegacy` on PyPI but I'm **not** associated with it. I did notice it says it's a fork with an altered `setup.py`, but I'm unsure what else that author changed to the library. As for it not picking up reactions, I'm not sure why because I tested some base similar code and it didn't have any issues.

**Code**
```py
@bot.event
async def on_message(message: discord.Message):
    if not message.author.bot:
        ctx = await bot.get_context(message)
        menu = ReactionMenu(ctx, back_button="◀️", next_button="▶️", config=ReactionMenu.STATIC)
        menu.add_page(discord.Embed(title="1"))
        menu.add_page(discord.Embed(title="2"))
        menu.add_page(discord.Embed(title="3"))
        await menu.start()
```

**Results**
![Discord_MAgzhsF9d7](https://user-images.githubusercontent.com/52070034/158268364-089bd5c6-64b7-408a-a43f-19e10cc29a92.gif)


This was tested with the last discord.py supported version of the library (`pip install reactionmenu==2.0.4`)
- reactionmenu `v2.0.4`
- discord.py `v1.7.3`
- dislash.py `v1.4.9`

**Comment by unadjusted** [comment]
- Installed reactionmenu `2.0.4`
- discord.py `1.7.3`
- dislash.py `1.4.9`

I just tested your code:
```py
@calc_chan.event
async def on_message(message: discord.Message):
    if not message.author.bot:
        ctx = await calc_chan.get_context(message)
        menu = ReactionMenu(ctx, back_button="◀️", next_button="▶️", config=ReactionMenu.STATIC)
        menu.add_page(discord.Embed(title="1"))
        menu.add_page(discord.Embed(title="2"))
        menu.add_page(discord.Embed(title="3"))
        await menu.start()
```
Result:
![image](https://user-images.githubusercontent.com/85350984/158331577-da5f22c9-50e5-4f56-badd-72d71fd4ef61.png)


I just changed the `if` statement:
```py
@calc_chan.event
async def on_message(message: discord.Message):
    if message.author.id == owo_user:
        ctx = await calc_chan.get_context(message)
        menu = ReactionMenu(ctx, back_button="◀️", next_button="▶️", config=ReactionMenu.STATIC)
        menu.add_page(discord.Embed(title="Page 1"))
        menu.add_page(discord.Embed(title="Page 2"))
        menu.add_page(discord.Embed(title="Page 3"))
        await menu.start()
```
Result:
![image](https://user-images.githubusercontent.com/85350984/158331385-f1400dc8-fd99-4d65-9921-57d9c4d697c6.png)

Some thought: _Could it be that it `wait_for the` reaction of the `owo_user` ?_ 
Would be my only guess here

**Comment by Defxult** [comment]
The `owo_user` meaning the OwO bot? If the bot is the one attempting to interact with the menu (do the pagination) it will not work. It’s specifically made not to interact with bots because of the potential accidental rate limit issues because bots practically do everything automated. So yes, it does have something to do with the `wait_for`; and that’s because the library verifies the user paginating is not a bot.

**Comment by unadjusted** [comment]
No it should pick up an `user` reaction, like myself.
Which does not work after the embed is sent `on_message`, and if the author is `owo_user`
It is totally fine that it does not pick up bots. It does not pick up any user reactions, when doing it like i showed above.

**Comment by Defxult** [comment]
> And have a friend send a message, and you try to react to it

Ahhh so that’s what you mean. Even with that it will not work. Only the person who initially sent the message to trigger the menu is allowed to control it. Unless of course `all_can_react` is set to `True`. As for you not knowing it was a thing, I did mention it in the [docs](https://github.com/Defxult/reactionmenu/tree/v2.0.4#options-of-the-reactionmenu-constructor-kwargs) 😄
