### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by nicholasyoannou** [Defxult/reactionmenu#35]
Hey, 

It's me again, would like to ask about reactionmenu moving to Discord.py. My bot is powered by Pycord, so things work very differently. I don't plan on moving across to Discord.py as my bot is fully coded using Pycord, it'd take a while to move everything along so I'm choosing to stay. But I really like your module.

Am wondering if your module currently supports slash commands for Pycord, version 3.0.1 I'm using. I want to make it so it replies with the menu through slash commands, but not necessarily sure how.

Hope you can help :)

**Comment by Defxult** [comment]
I haven't tested anything related to Pycord since the start of development for reactionmenu v3.1.0 so I'm unsure if they work for updated versions of Pycord. I don't plan on continuing development for other versions because that's too much to handle to go back and forth between two libraries with my limited amount of free time.

**Comment by nicholasyoannou** [comment]
Is there a way to use it for slash commands though? The menu sends but it doesn't reply to the original message, so Discord thinks that the bot didn't respond. Should be an easy thing, hope it's possible.
