### ISSUE TITLE
create_task() got an unexptected keyword argument 'name'

### ISSUE THREAD

**Issue by Arcanocito** [Defxult/reactionmenu#4]
I tried various ways of making the menu, either dynamic or static but without even adding a reaction i get this exception, pointed to the line where i use 'await menu.start(send_to = ctx.channel.id)'.

I tried changing the content of the pages, but i get this error every time.

Is this error caused by something in my code or a universal issue? The error message led me to believe that the keyword argument was caused by the package itself not my code, but I could be wrong.

Also adding a reaction does not switch pages, but I think it is due to the menu closing because of the exception.

I am sorry if this question is nooby, I am still new to this.

My discord.py version is 1.7.1 running the latest pip install of reactionmenu

![image](https://user-images.githubusercontent.com/76993550/118392573-9d660780-b63a-11eb-89e9-128ee57938ea.png)

**Comment by Defxult** [comment]
That error is happening because the `name` kwarg for `create_task` was not added until Python 3.8. See issue #3 in reference to this. The [docs were updated](https://github.com/Defxult/reactionmenu#python-38-or-higher-is-required) recently to reflect that. To fix this, you will have to update your Python.

**Comment by Arcanocito** [comment]
Ty, updated it and works now! :D
