### ISSUE TITLE
Reactionmenu does not seem to notice the reaction press on direct message

### ISSUE THREAD

**Issue by called2voyage** [Defxult/reactionmenu#6]
Thanks for adding the direct message support for me! I just tested it out, and it successfully sent the menu to a direct message, but when I click on the next page reaction it doesn't handle that action. The reaction stays and the page doesn't change. If you want to see how I'm using reactionmenu, you can look here starting on line 108: https://github.com/called2voyage/MyPronounBot/blob/master/MyPronounBot.py

**Comment by Defxult** [comment]
By default, the menu's `navigation_speed` is set to `ReactionMenu.NORMAL`, but in DM's that setting is overridden and the navigation speed is set to `ReactionMenu.FAST` (see the `navigation_speed` info section [here](https://github.com/Defxult/reactionmenu#options-of-the-reactionmenu-constructor-kwargs)). In DM's, bots cannot remove reactions from other users, so the bot not removing reactions in DM's is intentional. As for the page not changing, I looked at your code and I don't see any `intents`. [Intents](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0) are needed in order for this package to function properly (it is noted in the "about" section for this repo). Enable intents and it should work as intended.

**Comment by called2voyage** [comment]
Whoops! I forgot that I upgraded my discord version when I upgraded python. Thanks! I'll add intents.

**Comment by called2voyage** [comment]
Ok, I added messages, reactions, and guilds intents and it still won't change pages. I haven't committed the changes to github yet, so here's the updated portion:

`intents = Intents(messages=True, reactions=True, guilds=True)

load_dotenv()
TOKEN = os.getenv('DISCORD_TOKEN')

bot = commands.Bot(command_prefix='!mypronoun ', intents=intents)`

**Comment by Defxult** [comment]
The `members` intent is missing

**Comment by called2voyage** [comment]
That fixed it, thanks!
