### ISSUE TITLE
Got two Suggestions

### ISSUE THREAD

**Issue by sami0596** [Defxult/reactionmenu#7]
Would be great if you could add something like dynamic buttons, incase we don't know how many reactions is needed.
Example, let's say we have an unknown amount of rows.
And then, I want it to add a number reaction for each row.

Another suggestion is to add column, 
We have rows_requested
Maybe add something like column_requested.

**Comment by Defxult** [comment]
You'll have to provide a better explanation for the dynamic buttons because I don't quite understand the use case of adding a reaction for each row. The way you explained it, it sounds like it'll end up raising the `TooManyButtons` exception. 

It's not possible to have columns in an embed unless you're talking about fields. In addition to that there's no way for the package to know what each field should be named (the name parameter of a field is required), especially if the amount of data received turns out to be numerous pages . It's also worth mentioning that the amount of data fields can hold is half of what descriptions can.
